/**
 * Central Type Exports
 * Export all types from a single entry point
 */

// API Types
export type {
  ApiResponse,
  ApiError,
  PaginatedResponse,
  PaginationMeta,
  PaginationParams,
  SortParams,
  DateRangeFilter,
  ApiRequestConfig,
  UploadResponse,
  BulkOperationResponse,
  ValidationError,
  ApiVersion,
} from './api';

// User Types
export type {
  User,
  UserProfile,
  UserSettings,
  AuthUser,
  UserRegistration,
  UserLogin,
  OtpVerification,
  PasswordResetRequest,
  PasswordReset,
  PasswordChange,
  UserProfileUpdate,
  UserStats,
  UserActivity,
  UserNotification,
  UserRole,
  UserStatus,
} from './user';

// Store Types
export type {
  Store,
  StoreTemplate,
  StoreColors,
  StoreFonts,
  StoreSocialLinks,
  StoreCreate,
  StoreUpdate,
  StorePublicProfile,
  StorePublicStats,
  StoreAnalytics,
  TopProduct,
  RevenueByDay,
  OrdersByStatus,
  StoreSettings,
  StoreVerification,
  VerificationDocument,
  StoreSubscription,
  StoreMetrics,
  UsernameAvailability,
} from './store';

// Product Types
export type {
  Product,
  ProductVariation,
  ProductCreate,
  ProductUpdate,
  ProductWithStore,
  ProductFilters,
  ProductCard,
  ProductVariant,
  ProductInventory,
  ProductPricing,
  ProductImage,
  ProductCategory,
  ProductReview,
  ProductStats,
  BulkProductOperation,
  ProductImport,
  ProductExport,
  ProductAvailability,
  ProductStatus,
} from './product';

// Order Types
export type {
  Order,
  OrderStatus,
  PaymentStatus,
  OrderItem,
  OrderAddress,
  CheckoutData,
  CheckoutItem,
  CheckoutResponse,
  OrderWithStore,
  OrderFilters,
  OrderStatusUpdate,
  OrderStats,
  OrderTimelineEvent,
  OrderSummary,
  OrderDetails,
  OrderInvoice,
  OrderCancellation,
  OrderFulfillment,
  OrderExport,
  OrderNotification,
  OrderReport,
} from './order';

// Payment Types
export type {
  Payment,
  PaymentStatus as PaymentStatusEnum,
  PaymentMethod,
  PaymentVerification,
  PaymentDetails,
  MonnifyWebhookEvent,
  PaymentLink,
  PaymentAnalytics,
  BankAccount,
  BankAccountVerification,
  NigerianBank,
  Payout,
  PayoutStatus,
  PayoutRequest,
  Balance,
  Transaction,
  Refund,
  RefundRequest,
  PaymentSummary,
  PaymentRetry,
} from './payment';

// Analytics Types
export type {
  DashboardAnalytics,
  AnalyticsOverview,
  RevenueAnalytics,
  TimeSeriesData,
  ProductRevenueData,
  CategoryRevenueData,
  OrderAnalytics,
  StatusDistribution,
  ProductAnalytics,
  TopSellingProduct,
  LowPerformingProduct,
  ProductsByCategory,
  CustomerAnalytics,
  CustomerByLocation,
  TopCustomer,
  TrafficAnalytics,
  TrafficSource,
  TopPage,
  DeviceBreakdown,
  SalesReport,
  DateRange,
  DailySales,
  ProductSales,
  CustomerSales,
  TopPerformer,
  ConversionFunnel,
  FunnelStep,
  DropOffPoint,
  CohortAnalysis,
  Cohort,
  GrowthMetrics,
  RealTimeAnalytics,
  RecentOrder,
  AnalyticsComparison,
  AnalyticsPeriod,
  AnalyticsExportRequest,
} from './analytics';

// Re-export global types for convenience
export type {
  ReactChildren,
  AsyncComponent,
  LayoutComponent,
  PageComponent,
  ErrorComponent,
  LoadingComponent,
  NotFoundComponent,
  RouteHandler,
  MiddlewareFunction,
  UseHookReturn,
  UseMutationReturn,
  FormFieldValue,
  FormValues,
  TableColumn,
  FilterOption,
  SelectOption,
  BreadcrumbItem,
  NavigationItem,
  ToastType,
  ModalProps,
  DrawerProps,
  ChartDataPoint,
  TimePeriod,
  SortDirection,
  FileType,
  UploadStatus,
  Theme,
  Language,
  Currency,
  NigerianState,
  PartialBy,
  RequiredBy,
  DeepPartial,
  DeepReadonly,
  Nullable,
  Optional,
  Maybe,
  Awaited,
  Fn,
  AsyncFn,
} from './global';